# Generated by Django 4.2 on 2023-04-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_date', models.DateTimeField()),
                ('payment_type', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(default=None)),
                ('content_type', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='contenttypes.contenttype')),
            ],
        ),
    ]
