# Generated by Django 4.2 on 2023-04-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='staff',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
