# Generated by Django 4.2 on 2023-05-16 07:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerBaseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_name', models.CharField(choices=[('E1', 'First Test'), ('E2', 'Second Test'), ('E3', 'Examination')], default=None, max_length=255)),
                ('test_date', models.DateField()),
                ('grade', models.CharField(choices=[('A', 'Distinction'), ('B', 'Very Good'), ('C', 'Credit'), ('D', 'Pass'), ('E', 'Fair'), ('F', 'Fail')], default=None, max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsAndEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('news_title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=350)),
                ('content', models.TextField()),
                ('news_date', models.DateField()),
                ('news_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('student_identification_number', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('class_level', models.CharField(choices=[('SS1', 'Senior Scondary I'), ('SS2', 'Senior Scondary II'), ('SS3', 'Senior Scondary III')], default='SS1', max_length=3)),
                ('discipline', models.CharField(choices=[('ART', 'Art Study'), ('CMR', 'Commercial Study'), ('SCI', 'Science Study')], default='CMR', max_length=3)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('BN', 'Prefer not to say')], default='BN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('ENG', 'English Language'), ('MTS', 'Mathematics'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('BIO', 'Biology'), ('AGRIC', 'Agricultural Science'), ('ECON', 'Economics'), ('GOVT', 'Government'), ('CIVIC', 'Civic Education'), ('CRS', 'Christian Religious Studies'), ('IRK', 'Islamic Religious Studies'), ('LIT', 'Literature in English'), ('GEO', 'Geography'), ('HIST', 'History'), ('COMMC', 'Commerce'), ('ACCT', 'Accounting'), ('COMP', 'Computer Science'), ('FMST', 'Further Mathematics'), ('TD', 'Technical Drawing'), ('FART', 'Fine Arts'), ('MSC', 'Music'), ('FCH', 'French'), ('SPN', 'Spanish')], max_length=8)),
                ('description', models.TextField(null=True)),
                ('score', models.ManyToManyField(default=None, to='education.computerbasetest')),
            ],
        ),
        migrations.AddField(
            model_name='computerbasetest',
            name='student',
            field=models.ManyToManyField(to='education.student'),
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('awards', models.TextField()),
                ('graduation_year', models.DateField()),
                ('current_occupation', models.CharField(max_length=255)),
                ('student', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='education.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcedemicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_term', models.CharField(choices=[('T1', 'First Term'), ('T2', 'Second Term'), ('T3', 'Third Term')], default='T1', max_length=20)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='education.course')),
                ('student', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='education.student')),
            ],
        ),
    ]
