# Generated by Django 4.2 on 2023-04-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_day', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('BN', 'Prefer not to say')], default='BN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='NewsAndEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('news_date', models.DateField(auto_now_add=True)),
                ('course', models.ManyToManyField(to='education.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='education.student'),
        ),
        migrations.CreateModel(
            name='ComputerBaseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_time', models.TimeField(auto_now_add=True)),
                ('test_date', models.DateField(auto_now=True)),
                ('score', models.IntegerField()),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_name', models.CharField(max_length=255)),
                ('graduation_year', models.DateField(auto_now_add=True, verbose_name='Year')),
                ('current_occupation', models.CharField(max_length=255)),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='education.course')),
            ],
        ),
        migrations.CreateModel(
            name='AcedemicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=1)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('student', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='education.student')),
            ],
        ),
    ]
