# Generated by Django 4.2 on 2023-04-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acedemicreport',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='education.student'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='education.course'),
        ),
        migrations.AddField(
            model_name='computerbasetest',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='education.student'),
        ),
        migrations.AddField(
            model_name='newsandevent',
            name='course',
            field=models.ManyToManyField(to='education.course'),
        ),
    ]
