# Generated by Django 4.2 on 2023-04-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_day',
            new_name='birthday',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='education.course'),
        ),
    ]
